name: Epic Template
description: Create a new Epic issue, representing a collection of Features to reach a product goal
title: ""
labels: ["epic"]
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: Type to add Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      placeholder: Type to add Acceptance Criteria
    validations:
      required: true
  - type: textarea
    attributes:
      label: Features
      placeholder: "- [ ] Feature issue(s) to be part of this Epic"
