name: User Story Template
description: Create a new User Story issue, representing a small objective
title: ""
labels: ["user story"]
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: Type to add Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      placeholder: Type to add Acceptance Criteria
    validations:
      required: true